CREATE TABLE NOTIFICATIONTYPE
(
    ID BIGINT IDENTITY(1,1) PRIMARY KEY, 
    CODE NVARCHAR(255) NOT NULL UNIQUE,
)

insert into NOTIFICATIONTYPE
values ('LOGGIN'),('LOGOUT')

CREATE TABLE NOTIFICATION
(
    ID BIGINT IDENTITY(1,1) PRIMARY KEY, 
    MESSAGE NVARCHAR(MAx) NOT NULL,
    CREATEDBY  BIGINT NOT NULL,
    TYPEID BIGINT NOT NULL,
    CONSTRAINT FK_CREATEDBY_USER_ID FOREIGN KEY (CREATEDBY)
    REFERENCES [USER](ID),
    CONSTRAINT FK_TYPEID_USER_ID FOREIGN KEY (TYPEID)
    REFERENCES NOTIFICATIONTYPE(ID)  
)

--DROP TABLE NOTIFICATIONRECEPIANT
CREATE TABLE NOTIFICATIONRECEPIANT
(
    ID BIGINT IDENTITY(1,1) PRIMARY KEY, 
    USERID  BIGINT NOT NULL,
    NOTIFICATIONID BIGINT NOT NULL,
    SEEN BIT DEFAULT 0,
    CONSTRAINT FK_USERID_USER_ID FOREIGN KEY (USERID)
    REFERENCES [USER](ID),
    CONSTRAINT FK_NOTIFICATIONID_USER_ID FOREIGN KEY (NOTIFICATIONID)
    REFERENCES NOTIFICATION(ID)  
)

CREATE TABLE USERLOGGIN
(
    ID BIGINT IDENTITY(1,1) PRIMARY KEY, 
    USERID  BIGINT NOT NULL,
    IP VARCHAR(15),
    DEVICE NVARCHAR(255),
    ISLOGGIN BIT NOT NULL,
    CREATEdAT DATETIME2 DEFAULT getDate(),
    CONSTRAINT FK_USERLOGGIN_USERID_USER_ID FOREIGN KEY (USERID)
    REFERENCES [USER](ID)
)

